theme: jekyll-theme-cayman
title: Ian Ouellette - SWEN 101
description: My name is Ian Ouellette and this is my page for my SWEN 101 class. I am from Vermont and went to Otter Valley for High School. 
description: I enjoy games both video and tabletop, guitar, and cars (especially motorsport).
